# Generated by Django 3.1 on 2020-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.CharField(default='', max_length=130),
        ),
    ]
