# Generated by Django 3.1 on 2020-08-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='prent',
            new_name='parent',
        ),
    ]
